# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'bloggauravim'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-1125769-7'

menu:
- {name: 'Archive', url: 'archive.html'}
- {name: 'About Me',   url: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://www.github.com/reddragon'}
- {icon: 'twitter',    link: 'https://twitter.com/GauravML'}
- {icon: 'linkedin',   link: 'http://www.linkedin.com/in/gauravmenghani/'}
- {icon: 'envelope',   link: 'mailto:gaurav.menghani+blog@gmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
